name: unittest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: app.py           
      SECRET_KEY: secret_key
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install -r requirements.txt  
      - name: Run pytest
        run: |
          python3 -m pytest tests/
