name: unittest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: app.py           
      SECRET_KEY: secret_key
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: pytest -v

